name: CI Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Visa meddelande
      run: echo \"This is a small message about absolutly nothing. but it shows if the action works.\"
