name: CI Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Custom message
        run: echo "::notice::this is a message about nothing more then showing that the code works."
